package jp.developer.bbee.assemblepc.common

import jp.developer.bbee.assemblepc.domain.model.Assembly
import jp.developer.bbee.assemblepc.domain.model.Composition
import jp.developer.bbee.assemblepc.domain.model.Device
import jp.developer.bbee.assemblepc.domain.model.enums.DeviceType
import jp.developer.bbee.assemblepc.domain.model.toPrice

object Constants {
    const val BASE_URL = "https://www.pcbuilding.link/"

    val KANA_HALF_TO_FULL = mapOf(
        "ｱ" to "ア",
        "ｲ" to "イ",
        "ｳ" to "ウ",
        "ｴ" to "エ",
        "ｵ" to "オ",
        "ｶ" to "カ",
        "ｷ" to "キ",
        "ｸ" to "ク",
        "ｹ" to "ケ",
        "ｺ" to "コ",
        "ｻ" to "サ",
        "ｼ" to "シ",
        "ｽ" to "ス",
        "ｾ" to "セ",
        "ｿ" to "ソ",
        "ﾀ" to "タ",
        "ﾁ" to "チ",
        "ﾂ" to "ツ",
        "ﾃ" to "テ",
        "ﾄ" to "ト",
        "ﾅ" to "ナ",
        "ﾆ" to "ニ",
        "ﾇ" to "ヌ",
        "ﾈ" to "ネ",
        "ﾉ" to "ノ",
        "ﾊ" to "ハ",
        "ﾋ" to "ヒ",
        "ﾌ" to "フ",
        "ﾍ" to "ヘ",
        "ﾎ" to "ホ",
        "ﾏ" to "マ",
        "ﾐ" to "ミ",
        "ﾑ" to "ム",
        "ﾒ" to "メ",
        "ﾓ" to "モ",
        "ﾔ" to "ヤ",
        "ﾕ" to "ユ",
        "ﾖ" to "ヨ",
        "ﾗ" to "ラ",
        "ﾘ" to "リ",
        "ﾙ" to "ル",
        "ﾚ" to "レ",
        "ﾛ" to "ロ",
        "ﾜ" to "ワ",
        "ｦ" to "ヲ",
        "ﾝ" to "ン",
        "ｧ" to "ァ",
        "ｨ" to "ィ",
        "ｩ" to "ゥ",
        "ｪ" to "ェ",
        "ｫ" to "ォ",
        "ｬ" to "ャ",
        "ｭ" to "ュ",
        "ｮ" to "ョ",
        "ｯ" to "ッ",
        "ｰ" to "ー",
        "｡" to "。",
        "｢" to "「",
        "｣" to "」",
        "､" to "、",
        "･" to "・",
        "ｶﾞ" to "ガ",
        "ｷﾞ" to "ギ",
        "ｸﾞ" to "グ",
        "ｹﾞ" to "ゲ",
        "ｺﾞ" to "ゴ",
        "ｻﾞ" to "ザ",
        "ｼﾞ" to "ジ",
        "ｽﾞ" to "ズ",
        "ｾﾞ" to "ゼ",
        "ｿﾞ" to "ゾ",
        "ﾀﾞ" to "ダ",
        "ﾁﾞ" to "ヂ",
        "ﾂﾞ" to "ヅ",
        "ﾃﾞ" to "デ",
        "ﾄﾞ" to "ド",
        "ﾊﾞ" to "バ",
        "ﾋﾞ" to "ビ",
        "ﾌﾞ" to "ブ",
        "ﾍﾞ" to "ベ",
        "ﾎﾞ" to "ボ",
        "ﾊﾟ" to "パ",
        "ﾋﾟ" to "ピ",
        "ﾌﾟ" to "プ",
        "ﾍﾟ" to "ペ",
        "ﾎﾟ" to "ポ",
        "ｳﾞ" to "ヴ",
        "ﾜﾞ" to "ヷ",
        "ｦﾞ" to "ヺ",
    )

    val DEVICE_SAMPLE = Device(
        id = "1",
        device = DeviceType.MEMORY.key,
        name = "DDR4-3200 16GB x2",
        imgUrl = "https://example.com/pc_case.jpg",
        url = "https://example.com/pc_case",
        detail = "メモリの詳細",
        price = 10000.toPrice(),
        rank = 1,
        releaseDate = "2021-01-01",
        invisible = false,
        flag1 = null,
        flag2 = null,
        createdDate = null,
        lastUpdate = null,
    )

    val ASSEMBLY_SAMPLE = Assembly(
        id = 1,
        assemblyId = 1,
        assemblyName = "サンプル構成",
        deviceId = DEVICE_SAMPLE.id,
        deviceType = DEVICE_SAMPLE.device,
        deviceName = DEVICE_SAMPLE.name,
        deviceImgUrl = DEVICE_SAMPLE.imgUrl,
        deviceDetail = DEVICE_SAMPLE.detail,
        devicePriceSaved = DEVICE_SAMPLE.price,
        devicePriceRecent = DEVICE_SAMPLE.price,
    )

    val COMPOSITION_SAMPLE = Composition.of(
        assemblyId = ASSEMBLY_SAMPLE.assemblyId,
        assemblyName = ASSEMBLY_SAMPLE.assemblyName,
        reviewText = null,
        reviewTime = null,
        assemblies = listOf(ASSEMBLY_SAMPLE),
        devices = listOf(DEVICE_SAMPLE),
    )
}
